//! Pull request creation.

use mauns_core::{
    error::{MaunsError, Result},
    types::FileChange,
};
use serde::{Deserialize, Serialize};
use tracing::info;

use crate::client::GitHubClient;

/// Input for creating a pull request.
#[derive(Debug, Clone)]
pub struct PrRequest {
    pub owner: String,
    pub repo: String,
    pub head_branch: String,
    pub base_branch: String,
    pub task: String,
    pub summary: String,
    pub change_log: Vec<FileChange>,
}

/// Minimal representation of the GitHub PR response.
#[derive(Debug, Clone, Deserialize)]
pub struct PrResponse {
    pub html_url: String,
    pub number: u64,
}

#[derive(Serialize)]
struct CreatePrBody<'a> {
    title: &'a str,
    body: String,
    head: &'a str,
    base: &'a str,
}

/// Create a pull request and return the response.
///
/// The PR title is derived from the task description.
/// The PR body is built from the execution summary and the file change list.
/// No LLM output is used in either field.
pub async fn create_pull_request(client: &GitHubClient, req: &PrRequest) -> Result<PrResponse> {
    let title = pr_title(&req.task);
    let body = pr_body(&req.summary, &req.change_log);

    let path = format!("/repos/{}/{}/pulls", req.owner, req.repo);

    let payload = CreatePrBody {
        title: &title,
        body,
        head: &req.head_branch,
        base: &req.base_branch,
    };

    let response: PrResponse = client.post(&path, &payload).await?;

    info!(
        github = "pr",
        number = response.number,
        url = %response.html_url,
        "pull request created"
    );

    Ok(response)
}

/// Detect the default branch of a repository via the GitHub API.
pub async fn default_branch(client: &GitHubClient, owner: &str, repo: &str) -> Result<String> {
    #[derive(Deserialize)]
    struct RepoInfo {
        default_branch: String,
    }

    let path = format!("/repos/{owner}/{repo}");
    let info: RepoInfo = client.get(&path).await?;
    Ok(info.default_branch)
}

/// Parse `owner` and `repo` from a git remote URL.
///
/// Handles both HTTPS (`https://github.com/owner/repo.git`) and
/// SSH (`git@github.com:owner/repo.git`) formats.
pub fn parse_remote_url(url: &str) -> Result<(String, String)> {
    // Strip trailing `.git`.
    let url = url.trim_end_matches(".git");

    // HTTPS format.
    if let Some(rest) = url.strip_prefix("https://github.com/") {
        return split_owner_repo(rest);
    }

    // SSH format.
    if let Some(rest) = url.strip_prefix("git@github.com:") {
        return split_owner_repo(rest);
    }

    Err(MaunsError::GitHub(format!(
        "cannot parse owner/repo from remote URL '{url}'; \
         expected https://github.com/<owner>/<repo> or git@github.com:<owner>/<repo>"
    )))
}

fn split_owner_repo(s: &str) -> Result<(String, String)> {
    let mut parts = s.splitn(2, '/');
    let owner = parts
        .next()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| MaunsError::GitHub(format!("cannot extract owner from '{s}'")))?;
    let repo = parts
        .next()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| MaunsError::GitHub(format!("cannot extract repo from '{s}'")))?;
    Ok((owner.to_string(), repo.to_string()))
}

fn pr_title(task: &str) -> String {
    let truncated: String = task.chars().take(72).collect();
    format!("[mauns] {truncated}")
}

fn pr_body(summary: &str, changes: &[FileChange]) -> String {
    let mut body = String::new();

    body.push_str("## Summary\n\n");
    body.push_str(summary.trim());
    body.push_str("\n\n");

    body.push_str("## Files Modified\n\n");
    if changes.is_empty() {
        body.push_str("No file changes were recorded.\n");
    } else {
        for change in changes {
            if change.applied {
                body.push_str(&format!("- `{}` ({})\n", change.path, change.operation));
            }
        }
    }

    body.push_str("\n---\n");
    body.push_str("*Generated by [mauns](https://github.com/mauns/mauns)*\n");

    body
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_https_remote() {
        let (o, r) = parse_remote_url("https://github.com/alice/my-repo.git").unwrap();
        assert_eq!(o, "alice");
        assert_eq!(r, "my-repo");
    }

    #[test]
    fn parse_ssh_remote() {
        let (o, r) = parse_remote_url("git@github.com:alice/my-repo.git").unwrap();
        assert_eq!(o, "alice");
        assert_eq!(r, "my-repo");
    }

    #[test]
    fn invalid_remote_returns_error() {
        assert!(parse_remote_url("https://gitlab.com/alice/repo").is_err());
    }
}
